<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <AssemblyName>Dreamstreaming.TermsPlugin</AssemblyName>
    <RootNamespace>Dreamstreaming.TermsPlugin</RootNamespace>

    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>

    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Jellyfin.Controller" Version="10.11.8">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>

    <PackageReference Include="Jellyfin.Model" Version="10.11.8">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>

  </ItemGroup>

  <ItemGroup>

    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />

    <None Remove="Web\loginlinks.js" />
    <EmbeddedResource Include="Web\loginlinks.js" />

  </ItemGroup>

</Project>